name: Sync main with latest upstream W1 branch

on:
  schedule:
    # Every night at 02:17 UTC – change if you like
    - cron: '17 2 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # we need full history
          token: ${{ secrets.BOT_TOKEN }}

      - name: Configure Git identity
        run: |
          git config user.name  "bc-it-bot"
          git config user.email "bc-it-bot@users.noreply.github.com"

      - name: Ensure script is executable
        run: chmod +x .github/scripts/update_main_from_it.sh

      - name: Sync main from upstream
        run: |
          ./.github/scripts/update_main_from_it.sh